[build]
  command = "npm install --platform=linux --arch=x64 sharp && pnpm build"
  publish = "dist"

[build.environment]
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  PYTHON_VERSION = "3.12.3"
  NODE_VERSION = "20.17.0"
